[ -f ~/.bash_functions ] && source ~/.bash_functions


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# append to the history file,  rather than overwriting it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Enable some Bash 4 features when possible:
shopt -s "globstar" 2> /dev/null;
shopt -s "autocd" 2> /dev/null;

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.bash_completion ] && source ~/.bash_completion
[ -f ~/.bash_prompt ] && source ~/.bash_prompt

# Not version controlled for machine specific
# configuration.
[ -f ~/.bash_extra ] && source ~/.bash_extra